[package]
name = "simple_hook"
version = "0.1.0"
edition = "2021"

[dependencies]
"minhook" = { path = "../.." }

[dependencies.windows]
version = "0.37.0"
features = ["alloc", "Win32_Foundation", "Win32_UI_WindowsAndMessaging"]